<?xml version="1.0" encoding="utf-8"?><Database Name="health_alt" Class="HealthDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=health_alt;Persist Security Info=True;User ID=user" SettingsObjectName="Health.EFData.Properties.Settings" SettingsPropertyName="health_altConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admins" Member="Admins">
    <Type Name="Admins">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Users_Admins" Member="Users" ThisKey="UserId" OtherKey="UserId" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ThirdName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastLogin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastLogout" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Users_Admins" Member="Admins" ThisKey="UserId" OtherKey="UserId" Type="Admins" Cardinality="One" />
      <Association Name="Users_Doctors" Member="Doctors" ThisKey="UserId" OtherKey="UserId" Type="Doctors" Cardinality="One" />
      <Association Name="Users_Patients" Member="Patients" ThisKey="UserId" OtherKey="UserId" Type="Patients" Cardinality="One" />
      <Association Name="Users_ProfileStorage" Member="ProfileStorage" ThisKey="UserId" OtherKey="UserId" Type="ProfileStorage" />
      <Association Name="Users_ProfileStorageImage" Member="ProfileStorageImage" ThisKey="UserId" OtherKey="UserId" Type="ProfileStorageImage" />
      <Association Name="Roles_Users" Member="Roles" ThisKey="RoleId" OtherKey="RoleId" Type="Roles" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Candidates" Member="Candidates">
    <Type Name="Candidates">
      <Column Name="CandidateId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ThirdName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Pole" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PatientCard" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DataStorage" Member="DataStorage">
    <Type Name="DataStorage">
      <Column Name="PatientId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParameterId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Parameters_DataStorage" Member="Parameters" ThisKey="ParameterId" OtherKey="ParameterId" Type="Parameters" IsForeignKey="true" />
      <Association Name="Patients_DataStorage" Member="Patients" ThisKey="PatientId" OtherKey="UserId" Type="Patients" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DataStorageImage" Member="DataStorageImage">
    <Type Name="DataStorageImage">
      <Column Name="PatientId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParameterId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Parameters_DataStorageImage" Member="Parameters" ThisKey="ParameterId" OtherKey="ParameterId" Type="Parameters" IsForeignKey="true" />
      <Association Name="Patients_DataStorageImage" Member="Patients" ThisKey="PatientId" OtherKey="UserId" Type="Patients" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Diagnoses" Member="Diagnoses">
    <Type Name="Diagnoses">
      <Column Name="DiagnosisId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Diagnoses_ParametersDiagnoses" Member="ParametersDiagnoses" ThisKey="DiagnosisId" OtherKey="DiagnosisId" Type="ParametersDiagnoses" />
      <Association Name="Diagnoses_PatientsDiagnoses" Member="PatientsDiagnoses" ThisKey="DiagnosisId" OtherKey="DiagnosisId" Type="PatientsDiagnoses" />
    </Type>
  </Table>
  <Table Name="dbo.Doctors" Member="Doctors">
    <Type Name="Doctors">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SpecialityId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Doctors_DoctorsPatients" Member="DoctorsPatients" ThisKey="UserId" OtherKey="DoctorId" Type="DoctorsPatients" />
      <Association Name="Users_Doctors" Member="Users" ThisKey="UserId" OtherKey="UserId" Type="Users" IsForeignKey="true" />
      <Association Name="Specialty_Doctors" Member="Specialty" ThisKey="SpecialityId" OtherKey="SpecialityId" Type="Specialty" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DoctorsPatients" Member="DoctorsPatients">
    <Type Name="DoctorsPatients">
      <Column Name="PatientId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DoctorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Doctors_DoctorsPatients" Member="Doctors" ThisKey="DoctorId" OtherKey="UserId" Type="Doctors" IsForeignKey="true" />
      <Association Name="Patients_DoctorsPatients" Member="Patients" ThisKey="PatientId" OtherKey="UserId" Type="Patients" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.JournalDataStorage" Member="JournalDataStorage">
    <Type Name="JournalDataStorage">
      <Column Name="PatientId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParameterId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Start" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Finish" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Parameters_JournalDataStorage" Member="Parameters" ThisKey="ParameterId" OtherKey="ParameterId" Type="Parameters" IsForeignKey="true" />
      <Association Name="Patients_JournalDataStorage" Member="Patients" ThisKey="PatientId" OtherKey="UserId" Type="Patients" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Parameters" Member="Parameters">
    <Type Name="Parameters">
      <Column Name="ParameterId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NormalMin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NormalMax" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NormalBool" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NormalSelection" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsSelection" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsProfile" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsAnketa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Parameters_DataStorage" Member="DataStorage" ThisKey="ParameterId" OtherKey="ParameterId" Type="DataStorage" />
      <Association Name="Parameters_DataStorageImage" Member="DataStorageImage" ThisKey="ParameterId" OtherKey="ParameterId" Type="DataStorageImage" />
      <Association Name="Parameters_JournalDataStorage" Member="JournalDataStorage" ThisKey="ParameterId" OtherKey="ParameterId" Type="JournalDataStorage" />
      <Association Name="Parameters_ParametersDiagnoses" Member="ParametersDiagnoses" ThisKey="ParameterId" OtherKey="ParameterId" Type="ParametersDiagnoses" />
      <Association Name="Parameters_ParametersPeriod" Member="ParametersPeriod" ThisKey="ParameterId" OtherKey="ParameterId" Type="ParametersPeriod" />
      <Association Name="Parameters_ParametersSelection" Member="ParametersSelection" ThisKey="ParameterId" OtherKey="ParameterId" Type="ParametersSelection" />
      <Association Name="Parameters_PatientsParameters" Member="PatientsParameters" ThisKey="ParameterId" OtherKey="ParameterId" Type="PatientsParameters" />
      <Association Name="Parameters_ProfileStorage" Member="ProfileStorage" ThisKey="ParameterId" OtherKey="ParameterId" Type="ProfileStorage" />
      <Association Name="Parameters_ProfileStorageImage" Member="ProfileStorageImage" ThisKey="ParameterId" OtherKey="ParameterId" Type="ProfileStorageImage" />
      <Association Name="ParametersTypes_Parameters" Member="ParametersTypes" ThisKey="TypeId" OtherKey="TypeId" Type="ParametersTypes" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParametersDiagnoses" Member="ParametersDiagnoses">
    <Type Name="ParametersDiagnoses">
      <Column Name="DiagnosisId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParameterId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Diagnoses_ParametersDiagnoses" Member="Diagnoses" ThisKey="DiagnosisId" OtherKey="DiagnosisId" Type="Diagnoses" IsForeignKey="true" />
      <Association Name="Parameters_ParametersDiagnoses" Member="Parameters" ThisKey="ParameterId" OtherKey="ParameterId" Type="Parameters" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParametersPeriod" Member="ParametersPeriod">
    <Type Name="ParametersPeriod">
      <Column Name="PatientId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParameterId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Start" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="IntervalMinute" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DayId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumberMonth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WeekId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MonthId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Parameters_ParametersPeriod" Member="Parameters" ThisKey="ParameterId" OtherKey="ParameterId" Type="Parameters" IsForeignKey="true" />
      <Association Name="Patients_ParametersPeriod" Member="Patients" ThisKey="PatientId" OtherKey="UserId" Type="Patients" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParametersSelection" Member="ParametersSelection">
    <Type Name="ParametersSelection">
      <Column Name="ParameterId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AllowValue" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Parameters_ParametersSelection" Member="Parameters" ThisKey="ParameterId" OtherKey="ParameterId" Type="Parameters" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParametersTypes" Member="ParametersTypes">
    <Type Name="ParametersTypes">
      <Column Name="TypeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="ParametersTypes_Parameters" Member="Parameters" ThisKey="TypeId" OtherKey="TypeId" Type="Parameters" />
    </Type>
  </Table>
  <Table Name="dbo.Patients" Member="Patients">
    <Type Name="Patients">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MobilePhone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Pole" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PatientCard" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Patients_DataStorage" Member="DataStorage" ThisKey="UserId" OtherKey="PatientId" Type="DataStorage" />
      <Association Name="Patients_DataStorageImage" Member="DataStorageImage" ThisKey="UserId" OtherKey="PatientId" Type="DataStorageImage" />
      <Association Name="Patients_DoctorsPatients" Member="DoctorsPatients" ThisKey="UserId" OtherKey="PatientId" Type="DoctorsPatients" />
      <Association Name="Patients_JournalDataStorage" Member="JournalDataStorage" ThisKey="UserId" OtherKey="PatientId" Type="JournalDataStorage" />
      <Association Name="Patients_ParametersPeriod" Member="ParametersPeriod" ThisKey="UserId" OtherKey="PatientId" Type="ParametersPeriod" />
      <Association Name="Patients_PatientsDiagnoses" Member="PatientsDiagnoses" ThisKey="UserId" OtherKey="PatientId" Type="PatientsDiagnoses" />
      <Association Name="Patients_PatientsParameters" Member="PatientsParameters" ThisKey="UserId" OtherKey="PatientId" Type="PatientsParameters" />
      <Association Name="Users_Patients" Member="Users" ThisKey="UserId" OtherKey="UserId" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PatientsDiagnoses" Member="PatientsDiagnoses">
    <Type Name="PatientsDiagnoses">
      <Column Name="PatientId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DiagnosisId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Diagnoses_PatientsDiagnoses" Member="Diagnoses" ThisKey="DiagnosisId" OtherKey="DiagnosisId" Type="Diagnoses" IsForeignKey="true" />
      <Association Name="Patients_PatientsDiagnoses" Member="Patients" ThisKey="PatientId" OtherKey="UserId" Type="Patients" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PatientsParameters" Member="PatientsParameters">
    <Type Name="PatientsParameters">
      <Column Name="PatientId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParameterId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Patients_PatientsParameters" Member="Patients" ThisKey="PatientId" OtherKey="UserId" Type="Patients" IsForeignKey="true" />
      <Association Name="Parameters_PatientsParameters" Member="Parameters" ThisKey="ParameterId" OtherKey="ParameterId" Type="Parameters" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProfileStorage" Member="ProfileStorage">
    <Type Name="ProfileStorage">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParameterId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Parameters_ProfileStorage" Member="Parameters" ThisKey="ParameterId" OtherKey="ParameterId" Type="Parameters" IsForeignKey="true" />
      <Association Name="Users_ProfileStorage" Member="Users" ThisKey="UserId" OtherKey="UserId" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProfileStorageImage" Member="ProfileStorageImage">
    <Type Name="ProfileStorageImage">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParameterId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Parameters_ProfileStorageImage" Member="Parameters" ThisKey="ParameterId" OtherKey="ParameterId" Type="Parameters" IsForeignKey="true" />
      <Association Name="Users_ProfileStorageImage" Member="Users" ThisKey="UserId" OtherKey="UserId" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Roles">
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Roles_Users" Member="Users" ThisKey="RoleId" OtherKey="RoleId" Type="Users" />
    </Type>
  </Table>
  <Table Name="dbo.Specialty" Member="Specialty">
    <Type Name="Specialty">
      <Column Name="SpecialityId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Specialty_Doctors" Member="Doctors" ThisKey="SpecialityId" OtherKey="SpecialityId" Type="Doctors" />
    </Type>
  </Table>
</Database>